**Theoretical Questions:**

**Q.1 Explain the purpose and advantage of NumPy in scientific computing and data analysis.How does it enhances python's capabilities for numerical operations?**

**Purpose and Advantages:**

NumPy is powerful library for numerical computation.It provides support for multi-dimensional arrays and matrices,along with a collection of mathematical function to operate on these arrays.

**Enhancements to python**


*   Efficiency:
        
       NumPy arrays are more efficient than the python lists for large data sets as they uses less memory and allow faster data processing.

*   Vectorised operation:
     
       Numpy allows element wise operation without the use of vectorised loop.


*   Integration:

       NumPy integrates well with other scientific computing libraries such as SciPy and pandas,and is essential for machine learning and data analysing.



    








**Q.2 Compare and contrast np.mean() and np.average() functions in NumPy.When would You use one over the other?**



1.   np.mean():
     Calcuates mean of the array element along the specified axis excluding weights.
2.   np.average():
     Calculates weighted average.

*   When to use:

     Use np.mean()to claculate simple avearge.
     use np.avearge() when weight is given.





**Q.3Describe the methods for revrsing a Numpy array along different axes.Provide examples for 1D and 2D array.**



*   Reversing in 1D: Use slicing.Eg..arr[::-1]
*   Reversing in 2D:
    
    Rowwise(axis 0): arr[::-1,:]
    column-wise(axis 1): arr[:,::-1]



In [20]:
# Q.3 eg.
import numpy as np
arr_1d=np.array([1,2,3,4])[::-1]
arr_2d=np.array([[1,2],[3,4]])[::-1,1]
arr_1d


array([4, 3, 2, 1])

In [21]:

arr_2d

array([4, 2])

**Q.4 How can you determine the data type of elements in a numPy array?Discuss the importance of data types in memory management and performance.**



*   Determining data type:
        
      Use the dtype attribute. eg..arr.dtype.
*   Importance:
       
     Specifying data types helps in optimizing memory usage and computational speed,as smaller dta types use less,memory.
     Using appropriate data types improves performance.



**Q.5 Define ndarrays in numpy and explain their key features.How do they differ from standard python lists?**


*   **ndarray (n-dimensional array) :** It is a grid of values  witha specified
    number of dimensions and a fixed size.Each element in the ndarray has same data type.

*   **Key features of ndarray :**

1.   Suports mathematical and logical operations.
2.   Faster and more memory-efficient than python lists.

*   **Difference from python lists:** Unlike lists, ndarrays suport vectorised operation and have homogenous data types,which allow for efficient computation.





**Q.6Analyse the performance benefits of Numpy arrays over python lists over large scale numerical operations.**


1.   **Memory efficiency :**Numpy arrays consume less memory than lists as they are stored in contigous blocks.
2.   **Speed :** Numpy operation are faster becuse they are implemented in C and involves fewer function calls.

3.  **Vectorised operation :**Element wise operations on arrays eliminate the python loops,further improving the performance.






**Q.7 Compare vstack() and hstack() functions in numpy.Provide examples demonstrating their usage and output.**


*   **vstack():** stacks arrays vertically(along rows).
*   **hstack():** stacks arrays horizontally(along columns).






In [24]:
#eg...
arr1=np.array([1,2])
arr2=np.array([3,4])
np.vstack((arr1,arr2))


array([[1, 2],
       [3, 4]])

In [25]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4])

**Q.8 Explain the differnce between fliplr() and flipud() methods in numpy including their effects on various array dimensions.**



*   **flipud():** Flips the array verticall up to down.
Equvalent to reversing the order of rows.
*  **fliplr():** Flips the array horizontally left to right.Equivalent to reversing the order of columns.



In [26]:
#eg...
arr=np.array([[1,2],[3,5]])
np.flipud(arr)

array([[3, 5],
       [1, 2]])

In [27]:
np.fliplr(arr)

array([[2, 1],
       [5, 3]])

**Q.9 Discuss the functionality of the array_split() method in numPy.how does it handle uneven split?**


*   **Functionality :** array_split() divides an array into subarrays.It is useful when number of sections does not evenly divide the array.
* **Uneven splits :** If the array does not divide evenly,the final sub arrays will be smaller than the others.



In [28]:
#eg..
arr = np.array([1,2,3,4,5])
np.array_split(arr,3)


[array([1, 2]), array([3, 4]), array([5])]

**Q.10 Explain the concepts of vectorization and broadcasting in numpy.How do they contribute to efficent array operations?**


*  **Vectorization:** Eliminates explicit loops by applying operations directly on arrays.
*   **Broadcasting :**Expands the dimensions of smaller arrays to match larger arrays,allowing element-wise operations on differntly shaped arrays.

*   **Efficiency :** Both techniques minimize the need for python loops,making coputations faster and more memory-efficient.






**Practical Questions**

**Q.1  Create a 3x3 NumPy array with random integers between 1 and 100 .Then interchange the rows and columns.**


In [1]:
import numpy as np
array=np.random.randint(1,101,size =(3,3))
print("Original array: \n",array)

Original array: 
 [[ 2 76 81]
 [ 9 11 22]
 [87 74  2]]


In [2]:
Trans_array =array.T
print("Transposed array:\n",Trans_array)

Transposed array:
 [[ 2  9 87]
 [76 11 74]
 [81 22  2]]


**Q.2 Generate a 1D NumPy array with 10 elements.Reshape it into 2x5 array,then into 5x2 array.**

In [4]:
import numpy as np
arr_1d=np.arange(10)
print("1D Array:\n",arr_1d)

1D Array:
 [0 1 2 3 4 5 6 7 8 9]


In [5]:
arr_2x5=arr_1d.reshape(2,5)
print("2x5 Array :\n",arr_2x5)

2x5 Array :
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
arr_5x2=arr_1d.reshape(5,2)
print("5x2 Array :\n",arr_5x2)

5x2 Array :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**Q.3 Create a 4x4 Numpy array with random float values.Add a border of zeroes around it,resulting in a 6x6 array.**

In [8]:
arr_4x4=np.random.rand(4,4)
print("4x4 Array :\n",arr_4x4)

4x4 Array :
 [[0.87849504 0.13852202 0.73571516 0.47888002]
 [0.93224066 0.92667813 0.27813302 0.83179966]
 [0.81729298 0.02507646 0.21840116 0.08688684]
 [0.32811921 0.63296604 0.29702525 0.8868201 ]]


In [9]:
arr_6x6=np.pad(arr_4x4,pad_width=1,mode='constant',constant_values=0)
print("6x6 Array with zero border :\n",arr_6x6)

6x6 Array with zero border :
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.87849504 0.13852202 0.73571516 0.47888002 0.        ]
 [0.         0.93224066 0.92667813 0.27813302 0.83179966 0.        ]
 [0.         0.81729298 0.02507646 0.21840116 0.08688684 0.        ]
 [0.         0.32811921 0.63296604 0.29702525 0.8868201  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**Q.4 Using Numpy,create an array of integers from 10 to 60 with a step of 5.**

In [11]:
arr5=np.arange(10,61,5)
print("Array of integers from 10 to 60 with a step of 5 :\n",arr5)

Array of integers from 10 to 60 with a step of 5 :
 [10 15 20 25 30 35 40 45 50 55 60]


**Q.5 Create a numpy array of strings['python','numpy','pandas'].Apply diferent case transformations(uppercase,lowercase,title case,etc.) to each element.**

In [12]:
arr_str=np.array(['python','numpy','pandas'])
print("Original array:\n",arr_str)

Original array:
 ['python' 'numpy' 'pandas']


In [13]:
np.char.upper(arr_str)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [14]:
np.char.lower(arr_str)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [15]:
np.char.title(arr_str)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

**Q.6 Generate a numpy array of words.insert a space between each character of every word in the array.**

In [16]:
word_arr=np.array(['hello','world','numpy'])
print("Original array:\n",word_arr)

Original array:
 ['hello' 'world' 'numpy']


In [17]:
np.char.join('',word_arr)

array(['hello', 'world', 'numpy'], dtype='<U5')

**Q.7 Create two 2D Numpy arrays and perform element -wise addition,subtraction,multiplication,and division.**

In [3]:
import numpy as np
arr_2d1=np.array([[1,2,3],[4,5,6]])
arr_2d2=np.array([[6,9,8],[7,6,4]])
print("Array 1 :\n",arr_2d1)

Array 1 :
 [[1 2 3]
 [4 5 6]]


In [4]:
print("Array 2 :\n",arr_2d2)

Array 2 :
 [[6 9 8]
 [7 6 4]]


In [5]:
#Element wise subtraction
np.subtract(arr_2d1,arr_2d2)

array([[-5, -7, -5],
       [-3, -1,  2]])

In [6]:
#Element wise addition
np.add(arr_2d1,arr_2d2)

array([[ 7, 11, 11],
       [11, 11, 10]])

In [7]:
#Element wise multiplication
np.multiply(arr_2d1,arr_2d2)

array([[ 6, 18, 24],
       [28, 30, 24]])

In [8]:
#Element wise division
np.divide(arr_2d1,arr_2d2)

array([[0.16666667, 0.22222222, 0.375     ],
       [0.57142857, 0.83333333, 1.5       ]])

**Q.8 Use numpy to create a5x5 identity matrix,then extract its digonal elements.**

In [10]:
identity_matrix=np.eye(5)
print("5x5 Identity matrix :\n",identity_matrix)

5x5 Identity matrix :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
np.diag(identity_matrix)

array([1., 1., 1., 1., 1.])

**Q.9 Generate a numpy array of 100 random integers between 0 and 1000.Find and display all the prime numbers in this array.**

In [12]:
ran_arr=np.random.randint(0,1000,size=100)
print("Random Generated array are:\n",ran_arr)

Random Generated array are:
 [394 217 679 963 343 179 505 282 969 671 586 320 308 124 185  26 778 266
 643 761 460  68 639 145 910 267 265 621 452 888  89 253 315 473 613 665
 132 947 316 276 165 453 910 889 571 484 185 597 420 365 729 732 545   8
 967 655 536 816 962 916 730 658 919 867 909 194 719 290 260  94 473 312
 651 887 512 923 842 401 213 866 394 234 932 115 274 905 702 802 547 459
 630 484 485 626 602 776 996 317 315 866]


In [17]:
def is_prime(n):
  if n<2:
    return False
  for i in range(2,int (np.sqrt(n))+1):
    if n% i==0:
      return False
  return True

prime_number=[num for num in ran_arr if is_prime(num)]
print("Prime numbers in the array are:\n",prime_number)


Prime numbers in the array are:
 [179, 643, 761, 89, 613, 947, 571, 967, 919, 719, 887, 401, 547, 317]


**Q.10 create a 3x3 matrix with valuesnranging from 1 to 9.Then ,calculate the sum of each row and each column.**

In [24]:
mat_rix=np.arange(1,10).reshape(3,3)
print("Matrix :\n",mat_rix)

Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
#Sum of each row
np.sum(mat_rix,axis=1)

array([ 6, 15, 24])

In [26]:
#Sum of each column
np.sum(mat_rix,axis=0)

array([12, 15, 18])